#!/bin/bash -eu

set -o pipefail

readonly VERSION="${1:?}"

cd "$(git rev-parse --show-toplevel)"

cargo set-version "${VERSION}"

cargo upgrade
cargo update

cargo check
cargo test

git add Cargo.{toml,lock}

git commit -m "chore: version ${VERSION}"
git tag -m "Version ${VERSION}" "${VERSION}"

git cliff 1.0.0..HEAD > CHANGELOG.md
git add CHANGELOG.md
git commit --amend --no-edit

git tag -f -m "Version ${VERSION}" "${VERSION}"
