#!/bin/bash -eu

set -o pipefail

readonly VERSION=${1:?}


cd "$(git rev-parse --show-toplevel)"

sed -i "s/^\(version = \"\).*\(\"\)/\1$VERSION\2/w /dev/stdout" Cargo.toml
git add Cargo.toml

cargo update
git add Cargo.lock

git commit -m "chore: version ${VERSION}"
git tag -m "Version ${VERSION}" "${VERSION}"

git cliff 1.0.0..HEAD > CHANGELOG.md
git add CHANGELOG.md
git commit --amend --no-edit

git tag -f -m "Version ${VERSION}" "${VERSION}"
